client_config_backend: settings
client_config:
  client_id: 894125857880-h01idlcjb33ebq62ddsm10qik0rb00mk.apps.googleusercontent.com
  client_secret: FIyWtxUpUt18C9KMjzoOq1o2

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive